baseURL = 'https://marquessv.github.io/marquills'
languageCode = 'en-us'
title = 'Marquills 🪶'
theme = "monochrome"

[params]
  footer = "Copyright © 2022 by marquessv"
  enableMathJax = true
  author = "marquessv"

[build]
  writeStats = true
